import type { OpenAPIV3_1 } from 'openapi-types';

/**
 * OpenAPI metadata for tRPC procedures.
 * Includes index signature for tRPC meta compatibility.
 */
export interface OpenApiMeta {
  openapi?: {
    /** HTTP method for this endpoint */
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    /** URL path (use {param} for path parameters) */
    path: string;
    /** OpenAPI tags for grouping */
    tags?: string[];
    /** Short summary of the operation */
    summary?: string;
    /** Detailed description */
    description?: string;
    /** Whether this endpoint is deprecated */
    deprecated?: boolean;
    /** Content type for request body (default: application/json) */
    contentType?: string;
    /** Override response content type */
    responseContentType?: string;
    /** Custom response headers */
    responseHeaders?: Record<string, OpenAPIV3_1.HeaderObject>;
    /** Protect endpoint (adds security requirement) */
    protect?: boolean;
  };
  /** Index signature for tRPC meta compatibility */
  [key: string]: unknown;
}

/**
 * JSON Schema collection (version-agnostic type for Typia compatibility)
 */
export interface JsonSchemaCollection {
  schemas: object[];
  components?: unknown;
}

/**
 * Parser with embedded Typia JSON schema
 */
export interface TypiaParser<T> {
  (input: unknown): T;
  /** Embedded JSON schema generated by Typia at compile time */
  _typiaSchema?: JsonSchemaCollection;
  /** Marker to identify Typia parsers */
  _isTypiaParser?: true;
}

/**
 * Options for generating OpenAPI document
 */
export interface GenerateOpenApiDocumentOptions {
  /** API title */
  title: string;
  /** API version */
  version: string;
  /** Base URL for the API */
  baseUrl: string;
  /** Optional description */
  description?: string;
  /** OpenAPI servers configuration */
  servers?: OpenAPIV3_1.ServerObject[];
  /** Security schemes */
  securitySchemes?: Record<string, OpenAPIV3_1.SecuritySchemeObject>;
  /** Default security requirement */
  security?: OpenAPIV3_1.SecurityRequirementObject[];
  /** Additional tags */
  tags?: OpenAPIV3_1.TagObject[];
  /** Error response schema */
  errorResponseSchema?: OpenAPIV3_1.SchemaObject;
}

/**
 * Options for HTTP handler
 */
export interface OpenApiHandlerOptions {
  /** tRPC router */
  router: unknown;
  /** Function to create tRPC context */
  createContext: (opts: { req: unknown; res: unknown }) => Promise<unknown> | unknown;
  /** Called when an error occurs */
  onError?: (opts: { error: Error; path: string; req: unknown }) => void;
  /** Response transformer */
  responseMeta?: (opts: { data: unknown; errors: unknown[]; ctx: unknown }) => {
    status?: number;
    headers?: Record<string, string>;
  };
}

/**
 * Parsed path with parameters
 */
export interface ParsedPath {
  /** Path pattern with :param format */
  pattern: string;
  /** Parameter names in order */
  params: string[];
}

/**
 * HTTP method type
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

/**
 * Procedure type in tRPC
 */
export type ProcedureType = 'query' | 'mutation' | 'subscription';
